import type { ID } from '@vendure/core';
import { unifySlugs } from './unify-slugs';

/** One translation row of an entity, as the backfill reads it. */
export interface BackfillRow {
  id: ID;
  languageCode: string;
  slug: string | null;
  name: string | null;
}

export interface BackfillEntity {
  id: ID;
  rows: BackfillRow[];
}

/**
 * @description
 * - `FILLED`: empty slugs get the slug a sibling translation has. No URL changes.
 * - `REWRITTEN`: a non-empty slug is replaced by the canonical one, so that URL changes.
 * - `GENERATED`: no translation had a slug; one is generated by the slug strategy, with an empty
 *   `context`, from the default-language name, else the first name the entity has.
 * - `CONFLICT`: another entity owns the slug in a language that would get it, even after this run.
 *   Left unchanged.
 * - `NO_SLUG`: no translation had a slug and the name yields none. Left unchanged.
 */
export type SlugBackfillOutcome = 'FILLED' | 'REWRITTEN' | 'GENERATED' | 'CONFLICT' | 'NO_SLUG';

/**
 * @description
 * One entity in a {@link SlugBackfillReport}.
 */
export interface SlugBackfillEntry {
  entityId: ID;
  outcome: SlugBackfillOutcome;
  /** The slug every translation gets; `null` for `NO_SLUG`. */
  slug: string | null;
  /** Every translation's slug before the backfill. */
  previousSlugs: Array<{ languageCode: string; slug: string }>;
  /** Entities that own `slug` in a language this entity would write it to. */
  conflictsWith: ID[];
  /** Translation rows to write `slug` to. Empty unless the entry is applied. */
  rowIds: ID[];
}

/** Generates a slug for an entity with none, from the name in the given row. `''` if there is none. */
export type GenerateSlug = (entityId: ID, nameRow: BackfillRow | undefined) => Promise<string>;

const key = (languageCode: string, slug: string) => `${languageCode}\u0000${slug}`;

interface Pending {
  entity: BackfillEntity;
  entry: SlugBackfillEntry;
  slug: string;
  toWrite: BackfillRow[];
}

/**
 * Plans what the backfill writes, entity by entity, with the same rule the interceptor applies on
 * every write (`unifySlugs` with no input translations). Uniqueness is per language. Ownership is
 * simulated in memory: an applied entry releases the slugs it overwrites and claims the new one, and
 * blocked entries are retried until nothing changes, so a conflict is one that would remain after
 * the run. Of two entities after the same slug, the first wins.
 */
export async function planSlugBackfill(
  entities: readonly BackfillEntity[],
  channelDefaultLanguageCode: string | undefined,
  generate: GenerateSlug,
): Promise<SlugBackfillEntry[]> {
  const owners = new Map<string, Set<string>>();
  const ownersOf = (languageCode: string, slug: string) => {
    const k = key(languageCode, slug);
    const set = owners.get(k) ?? new Set<string>();
    owners.set(k, set);
    return set;
  };
  for (const entity of entities) {
    for (const row of entity.rows) {
      if (row.slug?.trim()) {
        ownersOf(row.languageCode, row.slug).add(String(entity.id));
      }
    }
  }

  const entries: SlugBackfillEntry[] = [];
  let pending: Pending[] = [];
  for (const entity of entities) {
    const rows = entity.rows.map((row) => ({ languageCode: row.languageCode, slug: row.slug ?? '' }));
    let slug = unifySlugs([], rows, channelDefaultLanguageCode)?.[0]?.slug;
    let outcome: SlugBackfillOutcome;
    if (slug !== undefined) {
      const overwritesASlug = entity.rows.some((row) => row.slug?.trim() && row.slug !== slug);
      outcome = overwritesASlug ? 'REWRITTEN' : 'FILLED';
    } else if (rows.some((row) => row.slug.trim())) {
      continue; // Already unified.
    } else {
      const nameRow =
        entity.rows.find((row) => row.languageCode === channelDefaultLanguageCode && row.name?.trim()) ??
        entity.rows.find((row) => row.name?.trim());
      slug = (await generate(entity.id, nameRow)) || undefined;
      outcome = slug ? 'GENERATED' : 'NO_SLUG';
    }

    const entry: SlugBackfillEntry = {
      entityId: entity.id,
      outcome,
      slug: slug ?? null,
      previousSlugs: rows,
      conflictsWith: [],
      rowIds: [],
    };
    entries.push(entry);
    if (slug) {
      pending.push({ entity, entry, slug, toWrite: entity.rows.filter((row) => row.slug !== slug) });
    }
  }

  const conflictsOf = ({ entity, slug, toWrite }: Pending) => {
    const conflicts = new Set<string>();
    for (const row of toWrite) {
      for (const owner of owners.get(key(row.languageCode, slug)) ?? []) {
        if (owner !== String(entity.id)) {
          conflicts.add(owner);
        }
      }
    }
    return conflicts;
  };
  let progressed = true;
  while (progressed) {
    progressed = false;
    const blocked: Pending[] = [];
    for (const item of pending) {
      if (conflictsOf(item).size > 0) {
        blocked.push(item);
        continue;
      }
      progressed = true;
      for (const row of item.toWrite) {
        if (row.slug?.trim()) {
          ownersOf(row.languageCode, row.slug).delete(String(item.entity.id));
        }
        ownersOf(row.languageCode, item.slug).add(String(item.entity.id));
      }
      item.entry.rowIds = item.toWrite.map((row) => row.id);
    }
    pending = blocked;
  }
  for (const item of pending) {
    item.entry.outcome = 'CONFLICT';
    item.entry.conflictsWith = [...conflictsOf(item)];
  }
  return entries;
}
